<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.openkawu</groupId>
        <artifactId>jfxium-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jfxium</artifactId>
    <packaging>jar</packaging>
    <name>JFXium Core</name>
    <description>Core UI components for JFXium</description>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-javafx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-antdesignicons-pack</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>compile-less-themes</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-light.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-light.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-dark</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-dark.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-dark.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-mui</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-mui.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-mui.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-shadcn</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-shadcn.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-shadcn.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-cyberpunk</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-cyberpunk.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-cyberpunk.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-custom</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-custom.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-custom.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-mui-compact</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-mui-compact.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-mui-compact.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-mui-dark</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-mui-dark.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-mui-dark.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-mui-dark-compact</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-mui-dark-compact.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-mui-dark-compact.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-light-compact</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-light-compact.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-light-compact.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-less-themes-dark-compact</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>npx</executable>
                            <arguments>
                                <argument>lessc</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/less/theme-dark-compact.less</argument>
                                <argument>${project.basedir}/src/main/resources/org/openkawu/jfxium/css/theme-dark-compact.css</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
